#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum SoftwareId {
    Homebrew,
    XcodeCommandLineTools,
    Brave,
    Firefox,
    Chrome,
    JetBrainsToolbox,
    Cursor,
    Windsurf,
    VisualStudioCode,
    ZedStable,
    ZedPreview,
    Raycast,
    Rustup,
    RustStable,
    RustNightly,
    CargoJust,
    CargoBinstall,
    CargoWatch,
    SimpleHttpServer,
    Nvm,
    Bun,
    Go,
    Flutter,
    AndroidStudio,
    ReactNativeCli,
    DioxusCli,
    YewCli,
    LeptosCli,
    ElectronForge,
    DockerDesktop,
    Postman,
    Yaak,
    Bruno,
    CodexCli,
    ClaudeCli,
    ClaudeMultiCli,
    KimiCli,
    GeminiCli,
    QwenCli,
    OpencodeCli,
}

pub struct SoftwareCategory {
    pub name: &'static str,
    pub entries: &'static [SoftwareId],
}

#[derive(Clone, Copy)]
pub struct SoftwareHandle {
    pub category: &'static str,
    pub id: SoftwareId,
}

pub fn flattened_handles() -> Vec<SoftwareHandle> {
    CATEGORIES
        .iter()
        .flat_map(|category| {
            category.entries.iter().map(move |id| SoftwareHandle {
                category: category.name,
                id: *id,
            })
        })
        .collect()
}

impl SoftwareId {
    pub fn key(&self) -> &'static str {
        match self {
            Self::Homebrew => "homebrew",
            Self::XcodeCommandLineTools => "xcode_clt",
            Self::Brave => "brave",
            Self::Firefox => "firefox",
            Self::Chrome => "chrome",
            Self::JetBrainsToolbox => "jetbrains_toolbox",
            Self::Cursor => "cursor",
            Self::Windsurf => "windsurf",
            Self::VisualStudioCode => "visual_studio_code",
            Self::ZedStable => "zed_stable",
            Self::ZedPreview => "zed_preview",
            Self::Raycast => "raycast",
            Self::Rustup => "rustup",
            Self::RustStable => "rust_stable",
            Self::RustNightly => "rust_nightly",
            Self::CargoJust => "cargo_just",
            Self::CargoBinstall => "cargo_binstall",
            Self::CargoWatch => "cargo_watch",
            Self::SimpleHttpServer => "simple_http_server",
            Self::Nvm => "nvm",
            Self::Bun => "bun",
            Self::Go => "go",
            Self::Flutter => "flutter",
            Self::AndroidStudio => "android_studio",
            Self::ReactNativeCli => "react_native_cli",
            Self::DioxusCli => "dioxus_cli",
            Self::YewCli => "yew_cli",
            Self::LeptosCli => "leptos_cli",
            Self::ElectronForge => "electron_forge",
            Self::DockerDesktop => "docker_desktop",
            Self::Postman => "postman",
            Self::Yaak => "yaak",
            Self::Bruno => "bruno",
            Self::CodexCli => "codex_cli",
            Self::ClaudeCli => "claude_cli",
            Self::ClaudeMultiCli => "claude_multi_cli",
            Self::KimiCli => "kimi_cli",
            Self::GeminiCli => "gemini_cli",
            Self::QwenCli => "qwen_cli",
            Self::OpencodeCli => "opencode_cli",
        }
    }

    pub fn name(&self) -> &'static str {
        match self {
            Self::Homebrew => "Homebrew",
            Self::XcodeCommandLineTools => "Xcode Command-Line Tools",
            Self::Brave => "Brave Browser",
            Self::Firefox => "Firefox",
            Self::Chrome => "Google Chrome",
            Self::JetBrainsToolbox => "JetBrains Toolbox",
            Self::Cursor => "Cursor",
            Self::Windsurf => "Windsurf",
            Self::VisualStudioCode => "Visual Studio Code",
            Self::ZedStable => "Zed (Stable)",
            Self::ZedPreview => "Zed (Preview)",
            Self::Raycast => "Raycast",
            Self::Rustup => "Rustup",
            Self::RustStable => "Rust Toolchain (Stable)",
            Self::RustNightly => "Rust Toolchain (Nightly)",
            Self::CargoJust => "cargo-just",
            Self::CargoBinstall => "cargo-binstall",
            Self::CargoWatch => "cargo-watch",
            Self::SimpleHttpServer => "simple-http-server (nightly)",
            Self::Nvm => "Node Version Manager (nvm)",
            Self::Bun => "Bun Runtime",
            Self::Go => "Go Toolchain",
            Self::Flutter => "Flutter SDK",
            Self::AndroidStudio => "Android Studio",
            Self::ReactNativeCli => "React Native CLI",
            Self::DioxusCli => "Dioxus CLI",
            Self::YewCli => "Yew CLI",
            Self::LeptosCli => "Leptos CLI",
            Self::ElectronForge => "Electron Forge",
            Self::DockerDesktop => "Docker Desktop",
            Self::Postman => "Postman",
            Self::Yaak => "Yaak",
            Self::Bruno => "Bruno",
            Self::CodexCli => "Codex CLI",
            Self::ClaudeCli => "Claude CLI",
            Self::ClaudeMultiCli => "Claude Multi CLI",
            Self::KimiCli => "Kimi CLI",
            Self::GeminiCli => "Gemini CLI",
            Self::QwenCli => "Qwen CLI",
            Self::OpencodeCli => "Opencode CLI",
        }
    }

    pub fn summary(&self) -> &'static str {
        match self {
            Self::Homebrew => "Package manager foundation for macOS.",
            Self::XcodeCommandLineTools => "Compilers and SDK headers from Apple.",
            Self::Brave => "Privacy-focused Chromium browser.",
            Self::Firefox => "Mozilla’s versatile browser.",
            Self::Chrome => "Google’s mainstream browser.",
            Self::JetBrainsToolbox => "Launcher for JetBrains IDEs (Android Studio).",
            Self::Cursor => "AI-native editor focused on flow with built-in agent.",
            Self::Windsurf => "Codeium’s AI pair-programming IDE.",
            Self::VisualStudioCode => "Microsoft’s extensible editor and IDE.",
            Self::ZedStable => "Zed editor stable channel.",
            Self::ZedPreview => "Zed editor preview channel.",
            Self::Raycast => "Productivity command palette for macOS.",
            Self::Rustup => "Rust toolchain installer.",
            Self::RustStable => "Sets Rust stable as default toolchain.",
            Self::RustNightly => "Installs nightly Rust toolchain.",
            Self::CargoJust => "Handy task runner for Rust projects.",
            Self::CargoBinstall => "Fast binary installer for cargo packages.",
            Self::CargoWatch => "Auto compile/test watcher for Rust.",
            Self::SimpleHttpServer => "Nightly-only HTTP dev server.",
            Self::Nvm => "Manage multiple Node.js versions.",
            Self::Bun => "All-in-one JS runtime/bundler.",
            Self::Go => "Google’s Go language toolchain.",
            Self::Flutter => "Google’s UI SDK for mobile & desktop.",
            Self::AndroidStudio => "Google’s official IDE for Android development.",
            Self::ReactNativeCli => "React Native project scaffolding CLI.",
            Self::DioxusCli => "Rust-based cross-platform UI tooling.",
            Self::YewCli => "CLI helpers for Yew web apps.",
            Self::LeptosCli => "Full-stack Leptos project manager.",
            Self::ElectronForge => "Electron scaffolding, packaging, and release tooling.",
            Self::DockerDesktop => "GUI and runtime for local Docker containers.",
            Self::Postman => "API design, testing, and collaboration suite.",
            Self::Yaak => "Lightweight REST and GraphQL API client.",
            Self::Bruno => "Text-based API collections and testing tool.",
            Self::CodexCli => "Command-line interface for Codex-style AI coding.",
            Self::ClaudeCli => "Anthropic Claude assistant from the terminal.",
            Self::ClaudeMultiCli => "Manage multiple Claude sessions and keys via CLI.",
            Self::KimiCli => "Terminal gateway to Kimi AI assistant.",
            Self::GeminiCli => "Interact with Google Gemini models from the CLI.",
            Self::QwenCli => "CLI helper for Alibaba Cloud’s Qwen assistants.",
            Self::OpencodeCli => "Dispatch open-source code LLMs via CLI workflows.",
        }
    }
}

pub const CATEGORIES: &[SoftwareCategory] = &[
    SoftwareCategory {
        name: "System Essentials",
        entries: &[SoftwareId::Homebrew, SoftwareId::XcodeCommandLineTools],
    },
    SoftwareCategory {
        name: "Browsers",
        entries: &[SoftwareId::Brave, SoftwareId::Firefox, SoftwareId::Chrome],
    },
    SoftwareCategory {
        name: "Editors & IDEs",
        entries: &[
            SoftwareId::JetBrainsToolbox,
            SoftwareId::Cursor,
            SoftwareId::Windsurf,
            SoftwareId::VisualStudioCode,
            SoftwareId::ZedStable,
            SoftwareId::ZedPreview,
        ],
    },
    SoftwareCategory {
        name: "Desktop Utilities",
        entries: &[SoftwareId::Raycast, SoftwareId::DockerDesktop],
    },
    SoftwareCategory {
        name: "API & Testing",
        entries: &[SoftwareId::Postman, SoftwareId::Yaak, SoftwareId::Bruno],
    },
    SoftwareCategory {
        name: "Rust Stack",
        entries: &[
            SoftwareId::Rustup,
            SoftwareId::RustStable,
            SoftwareId::RustNightly,
            SoftwareId::CargoJust,
            SoftwareId::CargoBinstall,
            SoftwareId::CargoWatch,
            SoftwareId::SimpleHttpServer,
            SoftwareId::DioxusCli,
            SoftwareId::YewCli,
            SoftwareId::LeptosCli,
        ],
    },
    SoftwareCategory {
        name: "JavaScript & Node",
        entries: &[SoftwareId::Nvm, SoftwareId::Bun, SoftwareId::ElectronForge],
    },
    SoftwareCategory {
        name: "Mobile / Cross-Platform",
        entries: &[
            SoftwareId::Flutter,
            SoftwareId::AndroidStudio,
            SoftwareId::ReactNativeCli,
        ],
    },
    SoftwareCategory {
        name: "AI Assistant CLIs",
        entries: &[
            SoftwareId::CodexCli,
            SoftwareId::ClaudeCli,
            SoftwareId::ClaudeMultiCli,
            SoftwareId::KimiCli,
            SoftwareId::GeminiCli,
            SoftwareId::QwenCli,
            SoftwareId::OpencodeCli,
        ],
    },
    SoftwareCategory {
        name: "Languages",
        entries: &[SoftwareId::Go],
    },
];
